config/routes.rb
Clouds::Application.routes.draw do
  resources :demos
  resources :users
  resources :sessions
  resources :clouds
  resources :platforms

  root :to => 'clouds#index'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get 'cloud/client_side_upload_response/:cloud_id' => 'cloud#client_side_upload_response'
  get 'platform/show_subtenant_details/:platform_id/:subtenant_name' => 'platform#show_subtenant_details'
  get 'platform/show_uid_metrics/:platform_id/:subtenant_name/:uid' => 'platform#show_uid_metrics'
  get 'cloud/:action/:cloud_id' => 'cloud#:action'
  get 'platform/:action/:platform_id' => 'platform#:action'
  get 'demos/:action/:id' => 'demos#:action'
  get 'demo/:action/:id' => 'demo#:action'
  get 'backup/restore/:email/:key/:password' => 'backup#restore', :constraints => { :email => /[^\/]+/ }
  get 'backup/import/Favorites/:api_type/:api/:email/:name' => 'backup#restore', :constraints => { :email => /[^\/]+/ }
  get 'backup/delete/Favorites/:api_type/:api/:email/:name' => 'backup#delete_cloud_data', :constraints => { :email => /[^\/]+/ }
  get 'backup/import/Demos/:email/:name' => 'backup#restore', :constraints => { :email => /[^\/]+/ }
  get 'backup/delete/Demos/:email/:name' => 'backup#delete_cloud_data', :constraints => { :email => /[^\/]+/ }
  get 'backup/delete_cloud_data/:email/:key' => 'backup#delete_cloud_data', :constraints => { :email => /[^\/]+/ }
  get 'backup/:action/favorite/:favorites/:favorite_id' => 'backup#:action'
  get 'backup/:action/favorite/:favorites/:favorite_id/:backup_action' => 'backup#:action'
  get 'backup/:action/demo/:demos/:favorites/:demo_id' => 'backup#:action'
  get 'backup/:action/demo/:demos/:favorites/:demo_id/:backup_action' => 'backup#:action'
  get 'backup/:action' => 'backup#:action'
  post 'platform/:action/:platform_id' => 'platform#:action'
  post 'cloud/:action/:cloud_id' => 'cloud#:action'
  post 'platform/:action/:platform_id/:task_id' => 'platform#:action'
  post 'cloud/:action/:cloud_id/:task_id' => 'cloud#:action'
  post 'demos/:action/:id' => 'demos#:action'
  post 'demo/:action/:id' => 'demo#:action'
  post 'backup/:action' => 'backup#:action'
  get 'clouds/:action/:id' => 'clouds#:action'

end

app/controllers/platform_controller.rb
class PlatformController < ApplicationController
  require "net/http"
  require "rexml/document"
  include REXML
  include Favorites

  before_action :set_platform, except: [:retrieve_favorites]

  # Show the logical reporting using the Atmos REST Management API
  def logical_view
    path = "/sysmgmt/tenants/#{@platform.tenant_name}/subtenants"
    @response, temp, temp = atmos_management_request("Get", Hash.new,  path, nil, "tenantadmin")
    path = "/sysmgmt/tenants/#{@platform.tenant_name}/scMetrics"
    @response_metrics, temp, temp = atmos_management_request("Get", Hash.new,  path, nil, "tenantadmin")
    respond_to do |format|
      format.html { render :logical_view }
    end
  end

  # Show the physical reporting using the Atmos REST Management API
  def physical_view
    path = "/sysmgmt/rmgs"
    response_rmgs, temp = atmos_management_request("Get", Hash.new,  path, nil, "sysadmin")
    rmgs = Array.new
    rmgs_hash = Hash.from_xml(response_rmgs.body)
    if rmgs_hash["rmgList"]["rmg"].instance_of? Array
      rmgs_hash["rmgList"]["rmg"].each do |elem|
        rmgs << elem["name"][0]
      end
    elsif rmgs_hash["rmgList"]["rmg"].instance_of? Hash
      rmgs << rmgs_hash["rmgList"]["rmg"]["name"][0]
    end
    nodes = Hash.new
    rmgs.each do |rmg|
      path = "/sysmgmt/rmgs/#{rmg}/nodes"
      response_nodes, temp = atmos_management_request("Get", Hash.new,  path, nil, "sysadmin")
      nodes[rmg] = Array.new
      nodes_hash = Hash.from_xml(response_nodes.body)
      nodes_hash["nodeList"]["node"].each do |elem|
       nodes[rmg] << elem["name"]
      end
    end
    uuids = Hash.new
    nodes.each do |rmg, values|
      uuids[rmg] = Hash.new
      values.each do |node|
        path = "/util/translate?scope=Node&input=name&value=#{node}&output=uuid"
        response_translate, temp = atmos_management_request("Get", Hash.new,  path, nil, "tenantadmin")
        uuids[rmg][node] = Hash.from_xml(response_translate.body)["translated_id"]
      end
    end
    @fs = Hash.new
    nodes.each do |rmg, values|
      @fs[rmg] = Hash.new
      values.each do |node|
        path = "/mgmt/disk_information_for_grid?node_uuid=#{uuids[rmg][node]}"
        response_fs, temp = atmos_management_request("Get", Hash.new,  path, nil, "tenantadmin")
        @fs[rmg][node] = Hash.new
        @temp = ActiveSupport::JSON.decode(response_fs.body)
        ActiveSupport::JSON.decode(response_fs.body)["aaData"].each do |disk|
          @fs[rmg][node][disk[0]] = Hash.new
          @fs[rmg][node][disk[0]]["device_path"] = disk[11]
          @fs[rmg][node][disk[0]]["dae"] = disk[1]
          @fs[rmg][node][disk[0]]["slot_id"] = disk[2]
          @fs[rmg][node][disk[0]]["free_capacity"] = disk[3]
          @fs[rmg][node][disk[0]]["percent_used"] = disk[5]
          @fs[rmg][node][disk[0]]["used_capacity"] = human_size_to_number(disk[6]).to_s
          @fs[rmg][node][disk[0]]["total_capacity"] = human_size_to_number(disk[7]).to_s
          @fs[rmg][node][disk[0]]["make"] = disk[8]
          @fs[rmg][node][disk[0]]["model"] = disk[9]
          @fs[rmg][node][disk[0]]["serial_number"] = disk[10]
          @fs[rmg][node][disk[0]]["atmos_services"] = disk[18]
          @fs[rmg][node][disk[0]]["current_status"] = disk[19]
        end
      end
    end

    respond_to do |format|
      format.html { render :physical_view }
    end
  end

  # Show the subtenant reporting using the Atmos REST Management API
  def show_subtenant_details
    path = "/sysmgmt/tenants/#{@platform.tenant_name}/subtenants/#{params[:subtenant_name]}"
    @response, temp = atmos_management_request("Get", Hash.new,  path, nil, "tenantadmin")
    path = "/sysmgmt/tenants/#{@platform.tenant_name}/#{params[:subtenant_name]}/scMetrics"
    @response_metrics, temp = atmos_management_request("Get", Hash.new,  path, nil, "tenantadmin")
    respond_to do |format|
      format.html { render :show_subtenant_details }
    end
  end

  # Show the uid reporting using the Atmos REST Management API
  def show_uid_metrics
    path = "/sysmgmt/tenants/#{@platform.tenant_name}/#{params[:subtenant_name]}/#{params[:uid]}/scMetrics"
    @response, temp = atmos_management_request("Get", Hash.new,  path, nil, "tenantadmin")
    respond_to do |format|
      format.html { render :show_uid_metrics }
    end
  end

  # Show the form to execute HTTP request
  def manual_request
    if @platform.platform_type == "Atmos"
      @path = "ex: /sysmgmt/rmgs"
      @headers = "One on each line. ex: {'x-atmos-subtenantname' => 't1subtenant'}. The headers needed for authentication will be added automatically for both POX and REST API"
    elsif @platform.platform_type == "Avamar"
        @path = "ex: /rest-api/versions"
        @headers = "One on each line. ex: {'key' => 'value'}. X-Concerto-Authorization will be added automatically"
    elsif @platform.platform_type == "ViPR"
      @path = "ex: /tenant"
      @headers = "One on each line. ex: {'key' => 'value'}. x-sds-auth-token will be added automatically"
    elsif @platform.platform_type == "vCloud Director"
      @path = "ex: /api/org"
      @headers = "One on each line. ex: {'key' => 'value'}. x-vcloud-authorization and Accept will be added automatically"
    end
    respond_to do |format|
      format.html { render "shared/manual_request" }
    end
  end

  # Execute the HTTP request
  def execute_manual_request
    http_method = params[:http_method]
    path = params[:path]
    headers = params[:headers]
    body = params[:body]
    params.each do |key, value|
      if key.start_with?("replace_") && !key.end_with?("_by")
        path.gsub!("XXX#{value}XXX",params[key + "_by"]) if params[key + "_by"] != ""
        headers.gsub!("XXX#{value}XXX",params[key + "_by"]) if params[key + "_by"] != ""
        body.gsub!("XXX#{value}XXX",params[key + "_by"]) if params[key + "_by"] != ""
      end
    end
    if params[:task_id]
      @task = Task.find(params[:task_id])
      @regexpressions = @task.regexpressions
    end
    begin
      if @platform.platform_type == "Atmos"
        headers_to_send = Hash.new
        headers.split("\n").each do |row|
          hash = eval(row)
          headers_to_send[hash.keys.first] = Array.new << hash.values.first.to_s
        end
        @response, @headers, @url = atmos_management_request(http_method, headers_to_send, path, body, params[:privilege].downcase)
      elsif @platform.platform_type == "Avamar"
        @response, @headers, @url = avamar_request(http_method, path, headers, body)
      elsif @platform.platform_type == "ViPR"
        @response, @headers, @url = vipr_request(http_method, path, headers, body)
      elsif @platform.platform_type == "vCloud Director"
        @response, @headers, @url = vcloud_request(http_method, path, headers, body)
      end
    rescue Exception => e
      @exception = e
    end
    respond_to do |format|
      format.js { render 'shared/execute_manual_request' }
    end
  end

  # Show the form to execute bulk HTTP requests
  def bulk_requests
    if @platform.platform_type == "Atmos"
      @path = "ex: /tenant_admin/list_sub_tenant"
      @headers = "One on each line. ex: {'x-atmos-subtenantname' => 't1subtenant'}. The headers needed for authentication will be added automatically for both POX and REST API"
    elsif @platform.platform_type == "ViPR"
      @path = "ex: /tenant"
      @headers = "One on each line. ex: {'key' => 'value'}. x-sds-auth-token will be added automatically"
    elsif @platform.platform_type == "vCloud Director"
      @path = "ex: /api/org"
      @headers = "One on each line. ex: {'key' => 'value'}. x-vcloud-authorization and Accept will be added automatically"
    end
    respond_to do |format|
      format.html { render "shared/bulk_requests" }
    end
  end

  # Execute the bulk HTTP requests
  def execute_bulk_requests
    begin
      @responses = Hash.new
      @headers = Hash.new
      @all_urls = Hash.new
      data = ActiveSupport::JSON.decode(params[:data])
      @detailed_results = data["detailed_results"]
      num_threads = data["threads"].to_i
      http_method = data["http_method"]
      data["lines_to_send"].threadify(num_threads) { |line|
        path = data["path"].gsub(/XXXCHANGEMEXXX/, line)
        headers = data["headers"].gsub(/XXXCHANGEMEXXX/, line)
        body = data["body"].gsub(/XXXCHANGEMEXXX/, line)
        data.each do |key, value|
          if key.start_with?("replace_") && !key.end_with?("_by")
            path.gsub!("XXX#{value}XXX",data[key + "_by"]) if data[key + "_by"] != ""
            headers.gsub!("XXX#{value}XXX",data[key + "_by"]) if data[key + "_by"] != ""
            body.gsub!("XXX#{value}XXX",data[key + "_by"]) if data[key + "_by"] != ""
          end
        end
        if @platform.platform_type == "Atmos"
          headers_to_send = Hash.new
          headers.split("\n").each do |row|
            hash = eval(row)
            headers_to_send[hash.keys.first] = Array.new << hash.values.first.to_s
          end
          @responses[line], @headers[line], @all_urls[line] = atmos_management_request(http_method, headers_to_send, path, body, data["privilege"].downcase)
        elsif @platform.platform_type == "Avamar"
          @responses[line], @headers[line], @all_urls[line] = avamar_request(http_method, path, headers, body)
        elsif @platform.platform_type == "ViPR"
          @responses[line], @headers[line], @all_urls[line] = vipr_request(http_method, path, headers, body)
        elsif @platform.platform_type == "vCloud Director"
          @responses[line], @headers[line], @all_urls[line] = vcloud_request(http_method, path, headers, body)
        end
      }
    rescue Exception => e
      @exception = e
    end
    respond_to do |format|
      format.js { render 'shared/execute_bulk_requests' }
    end
  end

  # Follow ViPR link returned in the response body
  def follow_link
    data = ActiveSupport::JSON.decode(params[:data])
    http_method = "Get"
    @path = data["path"]
    headers = ""

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController

  before_action :set_platform, only: [:show, :edit, :update, :destroy]

  # Show the platform APIs
  def index
    if current_user
      if Platform.exists?(user_id: @current_user.id)
        @platforms = @current_user.platforms.all
      end
    end
  end

  # Show actions available for a specific platform API
  def show
  end

  # Show the form to create a new platform API
  def new
    @platform = Platform.new
  end

  # Show the form to modify an existing platform API
  def edit
  end

  # Create a new platform API
  def create
    @platform = Platform.new(platform_params)
    current_user
    @platform.user_id = current_user.id

    respond_to do |format|
      if @platform.save
        format.html { redirect_to @platform, notice: 'Platform was successfully created.' }
        format.json { render action: 'show', status: :created, location: @platform }
      else
        format.html { render action: 'new' }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # Update an existing platform API
  def update
    respond_to do |format|
      if @platform.update(platform_params)
        format.html { redirect_to @platform, notice: 'Platform was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # Delete a platform API
  def destroy
    @platform.delete
    respond_to do |format|
      format.html { redirect_to platforms_url }
      format.json { head :no_content }
    end
  end

  private
    # Set the current platform API
    def set_platform
      @platform = Platform.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def platform_params
      params.require(:platform).permit(:platform_type, :ip, :sys_admin, :sys_admin_password, :tenant_name, :tenant_admin, :tenant_admin_password)
    end
end

app/helpers/platform_helper.rb
module PlatformHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/views/platforms/_form.html.erb
<%= form_for(@platform) do |f| %>
  <% if @platform.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@platform.errors.count, "error") %> prohibited this platform from being saved:</h2>

      <ul>
      <% @platform.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group">
    <span class="input-group-addon">Platform type</span>
    <%= f.select :platform_type, ["Atmos", "Avamar", "ViPR", "vCloud Director"], {}, {:class => "form-control"} %>
  </div>
  <br />
  <div class="input-group">
    <span class="input-group-addon">Ip</span>
    <%= f.text_field :ip, :class => "form-control" %>
  </div>
  <br />
  <div class="input-group">
    <span class="input-group-addon">SysAdmin</span>
    <%= f.text_field :sys_admin, :class => "form-control" %>
  </div>
  <br />
  <div class="input-group">
    <span class="input-group-addon">SysAdmin password</span>
    <%= f.password_field :sys_admin_password, :class => "form-control" %>
  </div>
  <br />
  <div class="input-group">
    <span class="input-group-addon">Tenant name</span>
    <%= f.text_field :tenant_name, :placeholder => "For Atmos, ViPR or vCloud Director (organization for vCloud Director if the user isn't a system administrator) ", :class => "form-control" %>
  </div>
  <br />
  <div class="input-group">
    <span class="input-group-addon">TenantAdmin</span>
    <%= f.text_field :tenant_admin, :placeholder => "Only for Atmos", :class => "form-control" %>
  </div>
  <br />
  <div class="input-group">
    <span class="input-group-addon">TenantAdmin password</span>
    <%= f.password_field :tenant_admin_password, :placeholder => "Only for Atmos", :class => "form-control" %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit nil, :class => "btn btn-primary" %>
  </div>
<% end %>
<br />
<%= link_to "Cancel", "/platforms", :class => "btn btn-default" %>

app/views/platforms/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Editing platform</div>
  <div class="panel-body">
		<%= render 'form' %>
	</div>
</div>

app/views/platforms/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Listing platforms</div>
  <div class="panel-body">
    <table class="table sortable">
      <thead>
        <tr>
          <th data-defaultsort="asc">Platform type</th>
          <th>Ip</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% if @platforms %>
          <% @platforms.each do |platform| %>
            <tr>
              <td><%= platform.platform_type %></td>
              <td><%= platform.ip %></td>
              <td><%= link_to 'Actions', platform, :class => "btn btn-primary" %></td>
              <td><%= link_to 'Edit', edit_platform_path(platform), :class => "btn btn-primary" %></td>
              <td><%= link_to 'Delete', platform, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/platforms/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Creating platform</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>
</div>

app/views/platforms/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Actions</div>
  <div class="panel-body">
		<%= render :partial => "/platform/show_platform" %>
    <% if (@platform.platform_type == "Atmos" || @platform.platform_type == "Avamar" || @platform.platform_type == "ViPR" || @platform.platform_type == "vCloud Director") && @platform.sys_admin.present? %>
      <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
          Requests <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Manual request', "/platform/manual_request/#{@platform.id}" %></li>
          <li><%= link_to 'Bulk requests', "/platform/bulk_requests/#{@platform.id}" %></li>
        </ul>
      </div>
    <% end %>
    <% if @platform.platform_type == "Atmos" && @platform.sys_admin.present? %>
      <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
          Reporting <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Logical view', "/platform/logical_view/#{@platform.id}" %></li>
          <li><%= link_to 'Physical view', "/platform/physical_view/#{@platform.id}" %></li>
        </ul>
      </div>
    <% end %>
	</div>
</div>
<%= link_to "Back", "/platforms", :class => "btn btn-default" %>