config/routes.rb
Clouds::Application.routes.draw do
  resources :demos
  resources :users
  resources :sessions
  resources :clouds
  resources :platforms

  root :to => 'clouds#index'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get 'cloud/client_side_upload_response/:cloud_id' => 'cloud#client_side_upload_response'
  get 'platform/show_subtenant_details/:platform_id/:subtenant_name' => 'platform#show_subtenant_details'
  get 'platform/show_uid_metrics/:platform_id/:subtenant_name/:uid' => 'platform#show_uid_metrics'
  get 'cloud/:action/:cloud_id' => 'cloud#:action'
  get 'platform/:action/:platform_id' => 'platform#:action'
  get 'demos/:action/:id' => 'demos#:action'
  get 'demo/:action/:id' => 'demo#:action'
  get 'backup/restore/:email/:key/:password' => 'backup#restore', :constraints => { :email => /[^\/]+/ }
  get 'backup/import/Favorites/:api_type/:api/:email/:name' => 'backup#restore', :constraints => { :email => /[^\/]+/ }
  get 'backup/delete/Favorites/:api_type/:api/:email/:name' => 'backup#delete_cloud_data', :constraints => { :email => /[^\/]+/ }
  get 'backup/import/Demos/:email/:name' => 'backup#restore', :constraints => { :email => /[^\/]+/ }
  get 'backup/delete/Demos/:email/:name' => 'backup#delete_cloud_data', :constraints => { :email => /[^\/]+/ }
  get 'backup/delete_cloud_data/:email/:key' => 'backup#delete_cloud_data', :constraints => { :email => /[^\/]+/ }
  get 'backup/:action/favorite/:favorites/:favorite_id' => 'backup#:action'
  get 'backup/:action/favorite/:favorites/:favorite_id/:backup_action' => 'backup#:action'
  get 'backup/:action/demo/:demos/:favorites/:demo_id' => 'backup#:action'
  get 'backup/:action/demo/:demos/:favorites/:demo_id/:backup_action' => 'backup#:action'
  get 'backup/:action' => 'backup#:action'
  post 'platform/:action/:platform_id' => 'platform#:action'
  post 'cloud/:action/:cloud_id' => 'cloud#:action'
  post 'platform/:action/:platform_id/:task_id' => 'platform#:action'
  post 'cloud/:action/:cloud_id/:task_id' => 'cloud#:action'
  post 'demos/:action/:id' => 'demos#:action'
  post 'demo/:action/:id' => 'demo#:action'
  post 'backup/:action' => 'backup#:action'
  get 'clouds/:action/:id' => 'clouds#:action'

end

app/models/demo.rb
class Demo < ActiveRecord::Base
	has_many :tasks, -> {order(:position)}, dependent: :destroy
	belongs_to :user
	attr_accessible :name, :description
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  include Favorites

	# Add a new task to a demo
  def add_task
  	@task = Task.new(params)
    current_user
    @task.user_id = current_user.id
  	@saved = false
    if @task.save
    	@saved = true
    end

    respond_to do |format|
    	format.js { render 'demo/execute_add_task' }
   	end
  end

	# Delete a task from a demo
  def delete_task
  	@task = Task.find(params[:id])
  	@task.destroy
  	@demo = Demo.find(@task.demo_id)

    respond_to do |format|
      format.js { render 'demo/delete_task' }
    end
  end

	# Re order a task in a demo before its previous task
  def up_task
  	@task = Task.find(params[:id])
  	@task.move_higher
  	@demo = Demo.find(@task.demo_id)

    respond_to do |format|
      format.js { render 'demo/up_or_down_task' }
    end
  end

	# Re order a task in a demo after its next task
  def down_task
  	@task = Task.find(params[:id])
  	@task.move_lower
  	@demo = Demo.find(@task.demo_id)

    respond_to do |format|
      format.js { render 'demo/up_or_down_task' }
    end
  end

	# Show more details about a task
  def show_task
  	@task = Task.find(params[:id])
  	@cloud = Cloud.find(@task.cloud_id) if @task.cloud_id
  	@platform = Platform.find(@task.platform_id) if @task.platform_id
  	@favorite = Favorite.find(@task.favorite_id)

    respond_to do |format|
      format.js { render 'demo/show_task' }
    end
  end

	# Execute an individual task
  def execute_task
  	@task = Task.find(params[:id])
  	@cloud = Cloud.find(@task.cloud_id) if @task.cloud_id
  	@platform = Platform.find(@task.platform_id) if @task.platform_id
  	@favorite = Favorite.find(@task.favorite_id)

    respond_to do |format|
      format.js { render 'demo/execute_task' }
    end
  end

	# Show the form to update the API associated to a task
  def update_api
  	@task = Task.find(params[:id])
  	current_user
  	@favorite = Favorite.find(@task.favorite_id)

    respond_to do |format|
      format.js { render 'demo/update_api' }
    end
  end

	# Update the API associated to a task
  def execute_update_api
		@task = Task.find(params[:id])
		@demo = Demo.find(@task.demo_id)
		if params[:all]
	  	@demo.tasks.each do |task|
				task.update_attribute(:cloud_id, params[:id_selected].to_i) if(params[:type] == "Cloud API" && params[:id_selected] != "")
				task.update_attribute(:platform_id, params[:id_selected].to_i) if(params[:type] == "Platform Management" && params[:id_selected] != "")
			end
		else
			@task.update_attribute(:cloud_id, params[:id_selected].to_i) if(params[:type] == "Cloud API" && params[:id_selected] != "")
			@task.update_attribute(:platform_id, params[:id_selected].to_i) if(params[:type] == "Platform Management" && params[:id_selected] != "")
		end

    respond_to do |format|
      format.js { render 'demo/execute_update_api' }
    end
  end

	# Show the form to add a regular expression to a task
  def add_regexpression
    @task = Task.find(params[:id])

    respond_to do |format|
      format.js { render 'demo/add_regexpression' }
    end
  end

	# Add a regular expression to a task
  def execute_add_regexpression
    @task = Task.find(params[:id])
    @regexpression = Regexpression.new(params)
    current_user
    @regexpression.user_id = current_user.id
    @regexpression.task_id = @task.id
    @regexpression.save
    @regexpressions = @task.regexpressions

    respond_to do |format|
      format.js { render 'demo/show_regexpressions' }
    end
  end

	# Delete a regular expression
  def delete_regexpression
    @regexpression = Regexpression.find(params[:id])
    @regexpression.delete

    respond_to do |format|
      format.js { render 'demo/delete_regexpression' }
    end
  end

	# Show all the regular expressions associated to a task
  def show_regexpressions
    @task = Task.find(params[:id])
    @regexpressions = @task.regexpressions

    respond_to do |format|
      format.js { render 'demo/show_regexpressions' }
    end
  end

	# Show the form to set the response codes expected for a task
  def show_response_codes
    @task = Task.find(params[:id])

    respond_to do |format|
      format.js { render 'demo/show_response_codes' }
    end
  end

	# Update the response codes expected for a task
  def execute_set_response_codes
    @task = Task.find(params[:id])
    @task.update_attribute(:response_codes, params[:response_codes])

    respond_to do |format|
      format.js { render 'demo/hide_response_codes' }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :description, :demo_id, :cloud_id, :platform_id, :favorite_id)
    end
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
  include Favorites

	before_action :set_demo, only: [:show, :edit, :update, :destroy]

	# Show the demos
	def index
    if current_user
      if Demo.exists?(user_id: @current_user.id)
        @demos = @current_user.demos.all
      end
    end
  end

	# Show the form to create a new demo
  def new
    @demo = Demo.new
  end

	# Create a new demo
  def create
    @demo = Demo.new(demo_params)
    current_user
    @demo.user_id = @current_user.id

    respond_to do |format|
      if @demo.save
        format.html { redirect_to @demo, notice: 'Demo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @demo }
      else
        format.html { render action: 'new' }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

	# Update a demo
  def update
    respond_to do |format|
      if @demo.update(demo_params)
        format.html { redirect_to @demo, notice: 'Demo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

	# Delete a demo
  def destroy
    @demo.destroy
    respond_to do |format|
      format.html { redirect_to demos_url }
      format.json { head :no_content }
    end
  end

  private
		# Set the current demo
  	def set_demo
      @demo = Demo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def demo_params
      params.require(:demo).permit(:name, :description)
    end
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/views/demos/_form.html.erb
<%= form_for(@demo) do |f| %>
  <% if @demo.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@demo.errors.count, "error") %> prohibited this demo from being saved:</h2>

      <ul>
      <% @demo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group">
    <span class="input-group-addon">Name</span>
    <%= f.text_field :name, :id => "name", :class => "form-control" %>
  </div>
  <br />
  <div class="field">
    <div class="input-group">
      <span class="input-group-addon">Description</span>
      <%= f.text_area :description, :rows => 10, :class => "form-control" %>
    </div>
  </div>
  <br />
  <br />
  <div class="actions">
    <%= f.submit nil, :class => "btn btn-primary", :onsubmit => "formvalidation();" %>
  </div>
<% end %>
<br />
<%= link_to "Cancel", "/demos", :class => "btn btn-default" %>
<script type="text/javascript">
  $(document).ready(function() {
    $('form').submit(function() {
      if(/^[A-Za-z0-9\s]+$/.test($("#name").val())) {
        return true;
      }
      else {
        window.alert("Only letters, numbers and space characters are allowed");
        return false;
      }
    });
  });
</script>

app/views/demos/_tasks.html.erb
<%
  @to_replace = Array.new
  regexpressions = Array.new
  regexpressions_by_task = Hash.new
  @demo.tasks.each do |task|
    regexpressions_by_task[task.id] = Array.new
    task.regexpressions.each do |regexpression|
      regexpressions << regexpression.name
    end
    Favorite.find(task.favorite_id).attributes.each_pair do |name, value|
      value.to_s.scan(/X{3}(.*?)X{3}/).each do |m|
        m.each do |v|
          regexpressions_by_task[task.id] << v
          @to_replace << v unless @to_replace.index(v) || regexpressions.index(v)
        end
      end
    end
  end
%>
<% if @to_replace.size > 0 %>
  <h2>Text to replace</h2>
  <br />
  <% i = 0 %>
  <% @to_replace.each do |value| %>
    <div class="field">
      <div class="input-group">
        <span class="input-group-addon"><%= value %></span>
        <%= hidden_field_tag "replace_#{i.to_s}", value, :class => "replace" %>
        <%= text_field_tag "replace_#{i.to_s}_by", nil, :class => "form-control by" %>
      </div>
    </div>
    <br />
    <% i += 1 %>
  <% end %>
<% end %>
<h2>Task list</h2>
<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Description</th>
      <th>Type</th>
      <th>API</th>
      <th>Id</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th>Response code</th>
    </tr>
  </thead>

  <tbody>
    <% @demo.tasks.each do |task| %>
      <% @task = task %>
      <tr id="check_variables_<%= task.id %>" style="display:none;"><%= render :partial => "demo/check_variables" %></tr>
      <tr id="task_<%= task.id %>">
        <td><%= task.id.to_s %></td>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td>
          <% if task.platform_id %>
            Platform Management
          <% elsif task.cloud_id %>
            Cloud API
          <% else %>
            Other Platform
          <% end %>
        </td>
        <td>
          <% if task.platform_id %>
            <%= Platform.find(task.platform_id).platform_type %>
          <% elsif task.cloud_id %>
            <%= Cloud.find(task.cloud_id).api %>
          <% else %>
            Other API
          <% end %>
        </td>
        <td>
          <% if task.platform_id %>
            <%= task.platform_id %>
          <% elsif task.cloud_id %>
            <%= task.cloud_id %>
          <% end %>
        </td>
        <td><% unless task == @demo.tasks.first %><%= link_to raw('<i class="glyphicon glyphicon-chevron-up"></i>'), url_for(:controller => 'demo', :action => 'up_task', :id => task.id), :remote => true, :class => "btn btn-default" %><% end %></td>
        <td>
          <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
              Actions<span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Show request', url_for(:controller => 'demo', :action => 'show_task', :id => task.id), :remote => true %></li>
              <li><a onclick="$('#request_<%= task.id %>').fadeOut();">Hide request</a></li>
              <li><%= link_to 'Update API', url_for(:controller => 'demo', :action => 'update_api', :id => task.id), :remote => true %></li>
              <li><%= link_to 'Add a regular expression', url_for(:controller => 'demo', :action => 'add_regexpression', :id => task.id), :remote => true %></li>
              <li><%= link_to 'Show regular expressions', url_for(:controller => 'demo', :action => 'show_regexpressions', :id => task.id), :remote => true %></li>
              <li><%= link_to 'Add response codes', url_for(:controller => 'demo', :action => 'show_response_codes', :id => task.id), :remote => true %></li>
            </ul>
          </div>
        </td>
        <td><% unless task == @demo.tasks.last %><%= link_to raw('<i class="glyphicon glyphicon-chevron-down"></i>'), url_for(:controller => 'demo', :action => 'down_task', :id => task.id), :remote => true, :class => "btn btn-default" %><% end %></td>
        <td><%= link_to 'Delete', url_for(:controller => 'demo', :action => 'delete_task', :id => task.id), :remote => true, :class => "btn btn-danger" %></td>
        <td id="play_<%= task.id %>" style="display:none;"><%= link_to raw('<i class="glyphicon glyphicon-play"></i>'), url_for(:controller => 'demo', :action => 'execute_task', :id => task.id), :remote => true, :class => "btn btn-primary execute", :id => "execute_task_" + task.id.to_s %></td>
        <td id="status_<%= task.id %>" class="status">
        </td>
      </tr>
      <tr id="add_regexpression_<%= task.id %>" style="display:none;"></tr>
      <tr id="show_regexpressions_<%= task.id %>" style="display:none;"></tr>
      <tr id="show_response_codes_<%= task.id %>" style="display:none;"></tr>
      <tr id="update_api_<%= task.id %>" style="display:none;"></tr>
      <tr id="request_<%= task.id %>" class="requests" style="display:none;"></tr>
    <% end %>
  </tbody>
</table>
<br />
<%= render :partial => "shared/favorites" %>
<script type="text/javascript">
  var timer;
  (function(){
    var values = new Array();
    $(".replace").each(function( index ) {
      values[$("#" + this.id).val()] = $("#" + this.id + "_by").val();
    });
    <% regexpressions_by_task.each do |task_id, regexpressions| %>
      var prerequisites = true;
      <% regexpressions.each do |regexpression| %>
        if(!values["<%= regexpression %>"]) {
          prerequisites = false;
        }
      <% end %>
      if(prerequisites) {
        $("#play_<%= task_id %>").fadeIn();
      }
      else {
        $("#play_<%= task_id %>").fadeOut();
      }
    <% end %>
    if(timer) {
      clearTimeout(timer);
    }
    timer = setTimeout(arguments.callee, 1000);
  })();
</script

app/views/demos/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Editing demo</div>
  <div class="panel-body">
		<%= render 'form' %>
	</div>
</div>

app/views/demos/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Listing demos</div>
  <div class="panel-body">
    <table class="table sortable">
      <thead>
        <tr>
          <th data-defaultsort="asc">Name</th>
          <th>Description</th>
          <th></th>
          <th></th>
          <th></th>
          <% if @s3 %>
            <th></th>
          <% end %>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% if @demos %>
          <% @demos.each do |demo| %>
            <tr>
              <td><%= demo.name %></td>
              <td><%= demo.description %></td>
              <td><%= link_to 'Edit', edit_demo_path(demo), :class => "btn btn-primary" %></td>
              <td><%= link_to 'Tasks', demo, :class => "btn btn-primary" %></td>
              <td><%= link_to 'Backup', "/backup/backup/demo/1/1/#{demo.id}", :class => "btn btn-primary" %></td>
              <% if @s3 %>
                <td><%= link_to 'Share', "/backup/backup/demo/1/1/#{demo.id}/share_demo", :remote => true, :class => "btn btn-primary" %></td>
              <% end %>
              <td><%= link_to 'Delete', demo, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/demos/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Creating demo</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>
</div>

app/views/demos/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Tasks</div>
  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
         <tr>
          <td><%= @demo.name %></td>
          <td><%= @demo.description %></td>
          <td><a href="javascript:void(0);" class="btn btn-primary" onclick="execute_all();"><i class="glyphicon glyphicon-play"></i></a></td>
        </tr>
      </tbody>
    </table>
    <div id="tasks">
      <%= render :partial => 'tasks' %>
    </div>
	</div>
</div>
<%= link_to "Back", "/demos", :class => "btn btn-default" %>
<script type="text/javascript">
  var buttons;

  function start_task(button) {
    if(button) {
      button.click();
      var intervalID = setInterval(function() {
        if($('#' + button.attr('id') + '_done').length > 0) {
          clearInterval(intervalID);
          start_task(buttons.shift());
        }
      }, 3000);
    }
  }
  function execute_all() {
    $(".status").hide();
    buttons = new Array();
    $(".execute").each(function(index) {
      buttons.push($(this));
    });
    start_task(buttons.shift());
  }
</script>