config/routes.rb
Clouds::Application.routes.draw do
  resources :demos
  resources :users
  resources :sessions
  resources :clouds
  resources :platforms

  root :to => 'clouds#index'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get 'cloud/client_side_upload_response/:cloud_id' => 'cloud#client_side_upload_response'
  get 'platform/show_subtenant_details/:platform_id/:subtenant_name' => 'platform#show_subtenant_details'
  get 'platform/show_uid_metrics/:platform_id/:subtenant_name/:uid' => 'platform#show_uid_metrics'
  get 'cloud/:action/:cloud_id' => 'cloud#:action'
  get 'platform/:action/:platform_id' => 'platform#:action'
  get 'demos/:action/:id' => 'demos#:action'
  get 'demo/:action/:id' => 'demo#:action'
  get 'backup/restore/:email/:key/:password' => 'backup#restore', :constraints => { :email => /[^\/]+/ }
  get 'backup/import/Favorites/:api_type/:api/:email/:name' => 'backup#restore', :constraints => { :email => /[^\/]+/ }
  get 'backup/delete/Favorites/:api_type/:api/:email/:name' => 'backup#delete_cloud_data', :constraints => { :email => /[^\/]+/ }
  get 'backup/import/Demos/:email/:name' => 'backup#restore', :constraints => { :email => /[^\/]+/ }
  get 'backup/delete/Demos/:email/:name' => 'backup#delete_cloud_data', :constraints => { :email => /[^\/]+/ }
  get 'backup/delete_cloud_data/:email/:key' => 'backup#delete_cloud_data', :constraints => { :email => /[^\/]+/ }
  get 'backup/:action/favorite/:favorites/:favorite_id' => 'backup#:action'
  get 'backup/:action/favorite/:favorites/:favorite_id/:backup_action' => 'backup#:action'
  get 'backup/:action/demo/:demos/:favorites/:demo_id' => 'backup#:action'
  get 'backup/:action/demo/:demos/:favorites/:demo_id/:backup_action' => 'backup#:action'
  get 'backup/:action' => 'backup#:action'
  post 'platform/:action/:platform_id' => 'platform#:action'
  post 'cloud/:action/:cloud_id' => 'cloud#:action'
  post 'platform/:action/:platform_id/:task_id' => 'platform#:action'
  post 'cloud/:action/:cloud_id/:task_id' => 'cloud#:action'
  post 'demos/:action/:id' => 'demos#:action'
  post 'demo/:action/:id' => 'demo#:action'
  post 'backup/:action' => 'backup#:action'
  get 'clouds/:action/:id' => 'clouds#:action'

end

app/models/cloud.rb
class Cloud < ActiveRecord::Base
	belongs_to :user
	belongs_to :platform
	has_many :tasks
	attr_accessible :api, :url, :ip_addresses, :port, :token, :shared_secret, :bucket, :platform_id
end

app/controllers/cloud_controller.rb
class CloudController < ApplicationController
  require "net/http"
  require "rexml/document"
  require "base64"
  require "hmac-sha1"
  require 'securerandom'
  include REXML
  include Favorites

  before_action :set_cloud, except: [:retrieve_favorites, :about]

  # Show information about this application
  def about
  end

  # Show the form to execute HTTP request
  def manual_request
    if @cloud
      if @cloud.api == "Atmos"
        @path = "ex: /rest/objects/objectid?info"
        @headers = "One on each line. ex: {'x-emc-meta' => 'tag_name1=value1,tag_name2=value2'}. x-emc-date, x-emc-uid and x-emc-signature will be added automatically"
      elsif @cloud.api == "Amazon"
        @path = "ex: /ObjectName"
        @headers = "One on each line. ex: {'Content-MD5' => '033bd94b1168d7e4f0d644c3c95e35bf'}. Date and Authorization will be added automatically"
      elsif @cloud.api == "Swift"
        @path = "ex: /container/ObjectName."
        @headers = "One on each line. ex: {'key' => 'value'}. X-Auth-Token will be added automatically"
      end
    else
      @path = ""
      @headers = "One on each line. ex: {'key' => 'value'}."
      @other = true
    end
    respond_to do |format|
      format.html { render "shared/manual_request" }
    end
  end

  # Execute the HTTP request
  def execute_manual_request
    http_method = params[:http_method]
    path = params[:path]
    headers = params[:headers]
    body = params[:body]
    params.each do |key, value|
      if key.start_with?("replace_") && !key.end_with?("_by")
        path.gsub!("XXX#{value}XXX",params[key + "_by"]) if params[key + "_by"] != ""
        headers.gsub!("XXX#{value}XXX",params[key + "_by"]) if params[key + "_by"] != ""
        body.gsub!("XXX#{value}XXX",params[key + "_by"]) if params[key + "_by"] != ""
      end
    end
    if params[:task_id]
      @task = Task.find(params[:task_id])
      @regexpressions = @task.regexpressions
    end
    begin
      if @cloud
        if @cloud.api == "Atmos"
          @response, @headers, @url = atmos_request(http_method, path, headers, body)
        elsif @cloud.api == "Amazon"
          @response, @headers, @url = amazon_request(http_method, path, headers, body)
        elsif @cloud.api == "Swift"
          @response, @headers, @url = swift_request(http_method, path, headers, body)
        end
      else
        url = path
        uri = URI.parse(url)
        headers_to_send = Hash.new
        headers.split("\n").each do |row|
          hash = eval(row)
          headers_to_send[hash.keys.first.downcase] = hash.values.first.to_s
        end
        if params[:user] != "" && params[:password] != ""
          login = Base64.urlsafe_encode64("#{params[:user]}:#{params[:password]}")
          headers_to_send["Authorization"] = "Basic #{login}"
        end
        @response = http_request(url, uri.port, http_method, headers_to_send, body)
        @headers = headers_to_send
      end
    rescue Exception => e
      @exception = e
    end
    respond_to do |format|
      format.js { render 'shared/execute_manual_request' }
    end
  end

  # Show the form to execute bulk HTTP requests
  def bulk_requests
    if @cloud
      if @cloud.api == "Atmos"
        @path = "ex: /rest/objects/objectid?info"
        @headers = "One on each line. ex: {'x-emc-meta' => 'tag_name1=value1,tag_name2=value2'}. x-emc-date, x-emc-uid and x-emc-signature will be added automatically"
      elsif @cloud.api == "Amazon"
        @path = "ex: /ObjectName"
        @headers = "One on each line. ex: {'Content-MD5' => '033bd94b1168d7e4f0d644c3c95e35bf'}. Date and Authorization will be added automatically"
      elsif @cloud.api == "Swift"
        @path = "ex: /container/ObjectName."
        @headers = "One on each line. ex: {'key' => 'value'}. X-Auth-Token will be added automatically"
      end
    else
      @path = ""
      @headers = "One on each line. ex: {'key' => 'value'}."
    end
    respond_to do |format|
      format.html { render "shared/bulk_requests" }
    end
  end

  # Execute the bulk HTTP requests
  def execute_bulk_requests
    begin
      @responses = Hash.new
      @headers = Hash.new
      @all_urls = Hash.new
      data = ActiveSupport::JSON.decode(params[:data])
      @detailed_results = data["detailed_results"]
      num_threads = data["threads"].to_i
      data["lines_to_send"].threadify(num_threads) { |line|
        path = data["path"].gsub(/XXXCHANGEMEXXX/, line)
        headers = data["headers"].gsub(/XXXCHANGEMEXXX/, line)
        body = data["body"].gsub(/XXXCHANGEMEXXX/, line)
        data.each do |key, value|
          if key.start_with?("replace_") && !key.end_with?("_by")
            path.gsub!("XXX#{value}XXX",data[key + "_by"]) if data[key + "_by"] != ""
            headers.gsub!("XXX#{value}XXX",data[key + "_by"]) if data[key + "_by"] != ""
            body.gsub!("XXX#{value}XXX",data[key + "_by"]) if data[key + "_by"] != ""
          end
        end
        if @cloud
          if @cloud.api == "Atmos"
            @responses[line], @headers[line], @all_urls[line] = atmos_request(data["http_method"], path, headers, body)
          elsif @cloud.api == "Amazon"
            @responses[line], @headers[line], @all_urls[line] = amazon_request(data["http_method"], path, headers, body)
          elsif @cloud.api == "Swift"
            @responses[line], @headers[line], @all_urls[line] = swift_request(data["http_method"], path, headers, body)
          end
        else
          url = path
          uri = URI.parse(url)
          headers_to_send = Hash.new
          headers.split("\n").each do |row|
            hash = eval(row)
            headers_to_send[hash.keys.first.downcase] = hash.values.first.to_s
          end
          @responses[line] = http_request(url, uri.port, data["http_method"], headers_to_send, body)
          @headers[line] = headers_to_send
        end
      }
    rescue Exception => e
      @exception = e
    end
    respond_to do |format|
      format.js { render 'shared/execute_bulk_requests' }
    end
  end

  # Show how to use the Amazon S3 multipart upload feature
  def multipart_upload
  end

  # Execute the Amazon S3 multipart upload
  def execute_multipart_upload
    begin
      filename = params[:file].original_filename
      @path = "/#{filename}"
      file_size = params[:file].size
      five_megabytes = 5 * 1024 * 1024
      @url_parts = Hash.new
      @responses_parts = Hash.new
      @headers_parts = Hash.new
      @response_init_upload, @headers_init_upload, @url_init_upload = amazon_request("Post", "/#{filename}?uploads", "", "")
      logger.info(@response_init_upload.inspect.to_s)
      if @response_init_upload.status == 200
        response_init_upload_hash = Hash.from_xml(@response_init_upload.body)
        upload_id = response_init_upload_hash["InitiateMultipartUploadResult"]["UploadId"]
        num_parts = (file_size.to_f / five_megabytes.to_f).ceil
        num_threads = params[:threads].to_i
        file = params[:file].open
        (1..num_parts).to_a.threadify(num_threads) { |thread|
          chunk = thread == num_parts ? file_size - ((num_parts - 1) * five_megabytes) : five_megabytes
          @responses_parts[thread], @headers_parts[thread], @url_parts[thread] = amazon_request("Put", "/#{filename}?partNumber=#{thread}&uploadId=#{upload_id}", "", file.read(chunk))
        }
        file.close
        @body = "<CompleteMultipartUpload>"
          (1..num_parts).to_a.each { |part_number|
            logger.info(@responses_parts[part_number].inspect)
            etag = @responses_parts[part_number].get_header("ETag").gsub(/^"|"$/, '')
            @body += "<Part>"
            @body += "<PartNumber>#{part_number}</PartNumber>"
            @body += "<ETag>#{etag}</ETag>"
            @body += "</Part>"
          }
        @body += "</CompleteMultipartUpload>"
        @response, @headers, @url_completing = amazon_request("Post", "/#{filename}?uploadId=#{upload_id}", "", @body)
      else
        @exception = "Can't initiate multipart upload. Status = #{@response_init_upload.status}"
      end
      logger.info(@response_init_upload.status.to_s)
    rescue Exception => e
      @exception = e
    end
    respond_to do |format|
      format.html { render :execute_multipart_upload }
    end
  end

  # Show how to use the Amazon S3 multipart upload feature from the web browser
  def client_side_multipart_upload
  end

  # Execute the Amazon S3 multipart upload from the web browser
  def execute_client_side_multipart_upload
    begin
      @headers = Hash.new
      @file_size = params["file_size"].to_i
      five_megabytes = 5 * 1024 * 1024
      @filename = params[:file_name]
      @num_threads = params[:threads].to_i
      @num_threads = 2 if @num_threads < 2
      @response_init_upload, @headers_init_upload = amazon_request("Post", "/#{@filename}?uploads", "", "")
      @uri = URI.parse(@cloud.url)
      if @response_init_upload.status == 200
        response_init_upload_hash = Hash.from_xml(@response_init_upload.body)
        @upload_id = response_init_upload_hash["InitiateMultipartUploadResult"]["UploadId"]
        @num_parts = (@file_size.to_f / five_megabytes.to_f).ceil
        @authorizations = Hash.new
        @headers = Hash.new
        @ip_addresses = Hash.new
        complete_multipart_upload_xml_size = 51
        (1..@num_parts).to_a.each do |part_number|
          complete_multipart_upload_xml_size += 85
          complete_multipart_upload_xml_size += part_number.to_s.length
          chunk = part_number == @num_parts ? @file_size - ((@num_parts - 1) * five_megabytes) : five_megabytes
          signature, @authorizations[part_number], @headers[part_number], @ip_addresses[part_number] = sign_amazon_request("Put", "/#{@filename}?partNumber=#{part_number}&uploadId=#{@upload_id}", "{'Content-Length' => '#{chunk.to_s}'}\n{'Content-Type' => 'application/x-www-form-urlencoded; charset=UTF-8'}", "", nil)
        end

app/controllers/clouds_controller.rb
class CloudsController < ApplicationController

  before_action :set_cloud, only: [:show, :edit, :update, :destroy]

  # Show the cloud APIs
  def index
    if current_user
      if Cloud.exists?(user_id: @current_user.id)
        @clouds = @current_user.clouds.all
      end
    else
        redirect_to :log_in
    end
  end

  # Show actions available for a specific cloud API
  def show
  end

  # Show the form to create a new cloud API
  def new
    @cloud = Cloud.new
  end

  # Show the form to modify an existing cloud API
  def edit
  end

  # Create a new cloud API
  def create
    @cloud = Cloud.new(cloud_params)
    current_user
    @cloud.user_id = current_user.id

    respond_to do |format|
      if @cloud.save
        format.html { redirect_to @cloud, notice: 'Cloud was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cloud }
      else
        format.html { render action: 'new' }
        format.json { render json: @cloud.errors, status: :unprocessable_entity }
      end
    end
  end

  # Update an existing cloud API
  def update
    respond_to do |format|
      if @cloud.update(cloud_params)
        format.html { redirect_to @cloud, notice: 'Cloud was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cloud.errors, status: :unprocessable_entity }
      end
    end
  end

  # Delete a cloud API
  def destroy
    @cloud.delete
    respond_to do |format|
      format.html { redirect_to clouds_url }
      format.json { head :no_content }
    end
  end

  # To return an error. Can be used by any controller
  def error
    @error = session[:error]
    session.delete(:error)
  end

  private
    # Set the current cloud API
    def set_cloud
      @cloud = Cloud.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cloud_params
      params.require(:cloud).permit(:api, :url, :ip_addresses, :port, :token, :shared_secret, :bucket, :platform_id)
    end
end

app/helpers/cloud_helper.rb
module CloudHelper
end

app/helpers/clouds_helper.rb
module CloudsHelper
end

app/views/clouds/_form.html.erb
<%= form_for(@cloud) do |f| %>
  <% if @cloud.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@cloud.errors.count, "error") %> prohibited this cloud from being saved:</h2>
      <ul>
      <% @cloud.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group">
    <span class="input-group-addon">Api</span>
    <%= f.select :api, ["Atmos","Amazon","Swift"], {}, {:class => "form-control"} %>
  </div>
  <br />
  <div class="input-group">
    <span class="input-group-addon">Url</span>
    <%= f.text_field :url, :class => "form-control" %>
  </div>
  <br />
  <div class="input-group">
    <span class="input-group-addon">IP addresses</span>
    <%= f.text_field :ip_addresses, :placeholder => "Optionnal, to perform load balancing (format: ['192.168.0.1', '192.168.0.2'])", :class => "form-control" %>
  </div>
  <br />
  <div class="input-group">
    <span class="input-group-addon">Port</span>
    <%= f.text_field :port, :class => "form-control" %>
  </div>
  <br />
  <div class="input-group">
    <span class="input-group-addon">Token</span>
    <%= f.text_field :token, :class => "form-control" %>
  </div>
  <br />
  <div class="input-group">
    <span class="input-group-addon">Shared secret</span>
    <%= f.text_field :shared_secret, :class => "form-control" %>
  </div>
  <br />
  <div class="input-group">
    <span class="input-group-addon">Bucket</span>
    <%= f.text_field :bucket, :placeholder => "For Amazon and Swift", :class => "form-control" %>
  </div>
  <br />
  <div class="input-group">
    <span class="input-group-addon">Platform (optional)</span>
    <%= f.select :platform_id, Platform.where("platform_type like 'ViPR' or platform_type like 'Atmos'").to_a.collect {|p| [ p.ip, p.id ] }, { include_blank: true }, {:class => "form-control"} %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit nil, :class => "btn btn-primary" %>
  </div>
<% end %>
<br />
<%= link_to "Cancel", "/clouds", :class => "btn btn-default" %>

app/views/clouds/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Editing cloud</div>
  <div class="panel-body">
		<%= render 'form' %>
	</div>
</div>

app/views/clouds/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Listing clouds</div>
  <div class="panel-body">
    <table class="table sortable">
      <thead>
        <tr>
          <th data-defaultsort="asc">Api</th>
          <th>Url</th>
          <th>Port</th>
          <th>Token</th>
          <th>Bucket</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% if @clouds %>
          <% @clouds.each do |cloud| %>
            <tr>
              <td><%= cloud.api %></td>
              <td><%= cloud.url %></td>
              <td><%= cloud.port %></td>
              <td><%= truncate(cloud.token, :length => 10) %></td>
              <td><%= cloud.bucket %></td>
              <td><%= link_to 'Actions', cloud, :class => "btn btn-primary" %></td>
              <td><%= link_to 'Edit', edit_cloud_path(cloud), :class => "btn btn-primary" %></td>
              <td><%= link_to 'Delete', cloud, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/clouds/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Creating cloud</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>
</div>

app/views/clouds/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Actions</div>
  <div class="panel-body">
    <%= render :partial => "/cloud/show_cloud" %>
    <% if @cloud.api == "Atmos" || @cloud.api == "Amazon" || @cloud.api == "Swift" %>
      <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
          Requests <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Manual request', "/cloud/manual_request/#{@cloud.id}" %></li>
          <li><%= link_to 'Bulk requests', "/cloud/bulk_requests/#{@cloud.id}" %></li>
        </ul>
      </div>
		<% end %>
    <% if @cloud.api == "Amazon" %>
      <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
          Amazon features <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Multipart upload', "/cloud/multipart_upload/#{@cloud.id}" %></li>
          <li><%= link_to 'Client-side upload using multipart upload', "/cloud/client_side_multipart_upload/#{@cloud.id}" %></li>
        </ul>
      </div>
    <% end %>
	</div>
</div>
<%= link_to "Back", "/clouds", :class => "btn btn-default" %>